# https://aka.ms/yaml
trigger: none

variables:
  workingDirectory: "$(System.DefaultWorkingDirectory)/naming-web/terraform"

stages:
  - stage: Lab
    jobs:
      - job: Destroy_Lab
        displayName: Destroy Lab environment
        pool: 'ccoe-vmss-lab-test2'
        variables:
          azurermServiceConnection: 'lab-ccoe-product-team'
        steps:
          - task: TerraformInstaller@0
            displayName: "Install Terraform CLI"
            inputs:
              terraformVersion: '1.3.0'

          - task: TerraformTaskV2@2
            displayName: "Terraform init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(workingDirectory)'
              backendServiceArm:  ${{ variables.azurermServiceConnection }}
              backendAzureRmStorageAccountName: 'stapdtconsumweu1l001'
              backendAzureRmResourceGroupName: 'rsg-pdtconsum-weu1-l-021'
              backendAzureRmContainerName: 'products-samples'
              backendAzureRmKey: 'ccoe.naming.web.lab.tfstate'

          - task: TerraformTaskV2@2
            displayName: "Terraform destroy"
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              workingDirectory: '$(workingDirectory)'
              commandOptions: '-var="environment=Lab"'
              environmentServiceNameAzureRM:  ${{ variables.azurermServiceConnection }}

  - stage: Corp
    jobs:
      - job: Destroy_Corp
        displayName: Destroy Corp environment
        pool: 'ccoe-container-corp'
        variables:
          azurermServiceConnection: 'corp-sub-product-p-prodcert-01'
        steps:
          - task: TerraformInstaller@0
            displayName: "Install Terraform CLI"
            inputs:
              terraformVersion: '1.3.0'

          - task: TerraformTaskV2@2
            displayName: "Terraform init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(workingDirectory)'
              backendServiceArm:  ${{ variables.azurermServiceConnection }}
              backendAzureRmResourceGroupName: 'rsg-prdcrt-weu1-p-021'
              backendAzureRmStorageAccountName: 'staprdcrtweu1p001'
              backendAzureRmContainerName: 'tfs-prdcrt-weu1-p-001'
              backendAzureRmKey: 'ccoe.naming.web.corp.tfstate'

          - task: TerraformTaskV2@2
            displayName: "Terraform destroy"
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              workingDirectory: '$(workingDirectory)'
              commandOptions: '-var="environment=Production"'
              environmentServiceNameAzureRM:  ${{ variables.azurermServiceConnection }}
