kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: my-cluster-role
rules:
- apiGroups: ["", "apps", "extensions", "storage.k8s.io"] # Add API groups as needed
  resources: ["*"] # Or specify specific resources
  verbs: ["*"] # Or specify specific verbs (get, list, create, update, delete, etc.)
